tokenizer_path: "AI-Sweden-Models/gpt-sw3-40b"  # Using Qwen model which has good multilingual support
output_dir: "test_validation_results"
log_dir: "test_logs"
sample_size: 100 # Reduced sample size for testing
max_workers: 2
z_threshold: 2.0
languages:
  - "swe"  # Base language code for Swedish

logging:
  max_size: 10485760
  backup_count: 5
  console_level: "INFO"
  file_level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_format: "tokenizer_validation_%Y%m%d_%H%M%S.log"

metrics:
  - "tokens_per_char"
  - "char_coverage"
  - "token_length"
  - "anomaly_detection"

anomaly_detection:
  method: "zscore"
  threshold: 2.0

resource_limits:
  max_memory_mb: 4096
  max_cpu_percent: 100
  cleanup_on_exit: true

figure_size:
  boxplot: [12, 8]
  heatmap: [10, 8]
  scatter: [10, 8]

dpi: 300

fallback_datasets:
  - "statmt/cc100"
  - "wikipedia"

output_formats:
  - "json"
  - "html"
  - "md" 